apiVersion: v1
kind: ConfigMap
metadata:
  name: covagro-config
  namespace: covagro
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,backend.covagro.svc.cluster.local"
  CORS_ALLOWED_ORIGINS: "http://localhost:30080,http://127.0.0.1:30080"
  POSTGRES_DB: covagro
  POSTGRES_USER: covagro
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  SEED_DATA: "true"
  SEED_PRODUCTOS: "1000"
  SEED_PEDIDOS: "3000"
